### ISSUE TITLE
dolly lora

### ISSUE THREAD

**Issue by camenduru** [camenduru/alpaca-lora-colab#1]
https://huggingface.co/EleutherAI/gpt-j-6B
https://huggingface.co/samwit/dolly-lora

https://www.databricks.com/blog/2023/03/24/hello-dolly-democratizing-magic-chatgpt-open-models.html
https://github.com/gururise/AlpacaDataCleaned

https://www.youtube.com/watch?v=AWAo4iyNWGc

https://colab.research.google.com/drive/1O1JjyGaC300BgSJoUbru6LuWAzRzEqCz?usp=sharing

**Comment by GeorvityLabs** [comment]
@camenduru do you know why the UI is buggey? 
like the loading animation keeps on popping , it stops working after a while.
seems to be unstable

**Comment by camenduru** [comment]
Hi @GeorvityLabs 👋 please try this repo https://github.com/deep-diver/Alpaca-LoRA-Serve
